---
- name: test
  hosts: all
  gather_facts: False

  tasks:
    - name: Add a file
      demo3:
        name: "hello_world"
        location: /tmp

    - name: remove file
      demo3:
        name: "hello_world"
        location: /tmp
        state: absent
...
